INSERT INTO PERSON(FIRSTNAME, LASTNAME, AGE) VALUES ( 'Ivan','Petrov',25 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, AGE) VALUES ( 'Ivan','Ivanov',35 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, AGE) VALUES ( 'Petr','Petrov',30 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, AGE) VALUES ( 'Petr','Sidorov',20 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, AGE) VALUES ( 'Pavel','Ivanov',18 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, AGE) VALUES ( 'Oleg','Pavlov',16 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, AGE) VALUES ( 'Viktor','Viktorov',10 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, AGE) VALUES ( 'Vasiliy','Pupkin',10 );